### ISSUE TITLE
Current Year Error

### ISSUE THREAD

**Issue by xemoka** [spieglt/fb-delete#1]
Thanks for this: was looking for a way to remove past content easily instead of just hiding or setting to 'Friends'. 

I figured I'd take it the whole way and remove 2018 content as well, but it errors out

```
Year 2018 not found. { Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at Promise (E:\fb-delete\node_modules\puppeteer\lib\Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (E:\fb-delete\node_modules\puppeteer\lib\Connection.js:197:12)
    at navigate (E:\fb-delete\node_modules\puppeteer\lib\Page.js:520:39)
    at Page.goto (E:\fb-delete\node_modules\puppeteer\lib\Page.js:500:7)
    at followLinkByContent (E:\fb-delete\index.js:99:14)
    at <anonymous>
  message: 'Protocol error (Page.navigate): Invalid parameters url: string value expected' }
```

Figured I'd post about it before digging too far into it.

**Comment by nhanb** [comment]
The `followLinkByContent()` function searches for an `<a>` tag whose inner text exactly matches the input. This fails when called with current year because in the timeline UI the current year is split into `This Month`, `April 2018`, `March 2018`, etc.

![screenshot_20180513_134736](https://user-images.githubusercontent.com/1446315/39964699-6978a57e-56b4-11e8-99c5-4cb1ede812ff.png)

**Comment by PavelValentov** [comment]
Also you have to use English facebook interface.

**Comment by spieglt** [comment]
Hey, sorry about this. I don't know why I never got notifications about the issues for this repo but I'm just now seeing them. Unfortunately I deleted my Facebook entirely so don't have an account to test with right now but I'll update here if I can get around to adjusting this.

**Comment by spieglt** [comment]
@xemoka @PavelValentov Sorry, it's quite late notice but this should be fixed in the latest commit.

**Comment by spieglt** [comment]
Meant to tag @nhanb also.
