### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by hugothimonier** [spieglt/fb-delete#14]
Hello,

First of all, thanks very much for the repo ! If it were to work on my machine it would be lovely.
I am not used to using javascript whatsover thus I have no idea how to debug this :  when trying to run your script everything seems to work fine until chromium opens : 
the log-ins are correctly written and should therefore allow the bot to connect itself. However, the bot validates my logins I then get the following error 

```bash
(node:13088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea what could cause such error to happen ?

Thanks anyway !

**Comment by spieglt** [comment]
@hugothimonier Hi, and thanks for trying it! I'm not sure offhand what's causing that. Was there anything else to the output, specifically a file and line number? I haven't used this since the last round of bug fixes but I'll see if I can soon.

**Comment by spieglt** [comment]
Confirmed that it's working for me, so I'll probably need a longer error message to helpful.

**Comment by hugothimonier** [comment]
Hello, 

Thank for such a quick answer ! I tried running it again, still without success. 
What happens is that Chromium loads, my email and password are passed correctly to facebook but then a small red message appears for a quick second on facebook (probably telling me i cannot log in but I am not sure since it disappear too quickly).

The full log in the shell is the following :
```bash
(node:4342) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at */Desktop/fb-delete-master/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/Connection.js:182:12)
    at navigate (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.goto (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/helper.js:112:23)
    at followLinkByContent (*/Desktop/fb-delete-master/index.js:104:14)
  -- ASYNC --
    at Frame.<anonymous> (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (*/Desktop/fb-delete-master/node_modules/puppeteer/lib/helper.js:112:23)
    at followLinkByContent (*/Desktop/fb-delete-master/index.js:104:14)
    at async next (*/Desktop/fb-delete-master/index.js:29:3)
    at async main (*/Desktop/fb-delete-master/index.js:24:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Regarding my machine if that's of any help

```bash
ProductName:	Mac OS X
ProductVersion:	10.14.6
Kernel Version: Darwin 18.7.0
```
Thanks !

**Comment by spieglt** [comment]
Ah, another issue I forgot about: is your account language set to `English (US)`? You may need to do that temporarily. I forgot to add a note about it to the readme last time this came up.

**Comment by hugothimonier** [comment]
I believe you did include it in the README, because I have changed my facebook to ``English (US)`` !

**Comment by spieglt** [comment]
Ah duh so I did haha

**Comment by spieglt** [comment]
So it looks like it's failing when trying to go to the `Filter` link from https://mbasic.facebook.com/allactivity. If you log in and visit that URL in Chrome, do you see a Filter link at the top under Activity Log? I'm not sure what else to try right now honestly.

**Comment by hugothimonier** [comment]
Yep there is the filter appearing. But the bot never gets to this page, he is stuck after trying to connect to facebook.
I thought I knew what caused the problem, it seemed that although my default language on facebook was set to english, the default language of chromium launched by puppeteer was french (my mother tongue). I tried changing it manually on chromium while it was open, but as I excpected it does not save any setting modifications. I also tried changing your ``index.js`` file by adding ``await page.setExtraHTTPHeaders({
     'Accept-Language': 'en'
   });`` as follows :
```javascript
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 100
  });
  page = await browser.newPage();
  await page.setExtraHTTPHeaders({
     'Accept-Language': 'en'
   });
```
It does change the language of the browser, but the bot still fails to connect to facebook. 

For instance, I get this message for a quick second and then it disappears.
![Capture d’écran 2021-01-27 à 21 21 15](https://user-images.githubusercontent.com/45941221/106048969-da3adc80-60e5-11eb-9a54-579a2df913d5.png)

**Comment by spieglt** [comment]
Ah, interesting... another option I guess would be to replace "Filter" and the other strings it's looking for with their French equivalents. I see you've forked it so maybe that would be easier than trying to change the Puppeteer browser's language (which is probably taking its cue from your OS language setting).

**Comment by spieglt** [comment]
And even if you never saw the filter link, I have to believe that the bot got that far because of this from your output: `at async next (*/Desktop/fb-delete-master/index.js:29:3)`. That line is here: https://github.com/spieglt/fb-delete/blob/master/index.js#L29.

**Comment by hugothimonier** [comment]
Well this does not seem to work either :(.

**Comment by spieglt** [comment]
Damn... Well sorry to hear, and thanks for helping troubleshoot it. I think the problem must still be related to the OS and Puppeteer-Chromium being set to French. I could help investigate over screenshare next week or something, though I expect we're in very different time zones.

**Comment by austinjhunt** [comment]
Hi @spieglt  and @hugothimonier , just an update! I ran into this issue as well. Turns out it was a timeout issue for the page.goto function call. So, for each of the main .goto(<link>) calls, I simply added the following as a second argument after the link and now it's working perfectly. 
```
{
    waitUntil: "load",
    timeout: 0,
  }
```

Makes sense that it wasn't showing up consistently for both of you, seems like it would depend on how quickly your browser is loading the pages.

**Comment by austinjhunt** [comment]
I have also added a conditional statement to the end of the followLinkByContent(content) method in index.js, because in my case it was failing in cases where the link was undefined: 


```
if (link != undefined) { 
    await page.goto(link, { waitUntil: "load", timeout: 0 });
  }
```

**Comment by spieglt** [comment]
Awesome, thanks for the PR!
