### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by xtremehume** [spieglt/fb-delete#7]
> (node:18746) UnhandledPromiseRejectionWarning: TypeError: puppeteer.launch is not a function
>     at main (/Users/[  ]/Documents/GitHub/fb-delete/index.js:11:35)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:18746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:18746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by spieglt** [comment]
Not sure about this. Did you `npm install`?
